version: '3'
services:
  api:
    image: 'localhost:5000/flanks/api:1.0'
    build: ./api
    ports:
      - "6501:6501"
    labels:
      kompose.service.type: LoadBalancer
    environment:
      - "PORT=6501"
    env_file:
      - environment.env
    depends_on:
      - database
    command: ./dockerize -wait tcp://database:27017 -timeout 5m python main.py
  fetch:
    image: 'localhost:5000/flanks/fetch:1.0'
    build: ./fetch
    env_file:
      - environment.env
    depends_on:
      - database
      - queue
    command: ./dockerize -wait tcp://database:27017 -wait tcp://queue:5672 -timeout 5m sh main.sh
  sheets:
    image: 'localhost:5000/flanks/sheets:1.0'
    build: ./sheets
    env_file:
      - environment.env
    depends_on:
      - database
      - queue
    command: ./dockerize -wait tcp://database:27017 -wait tcp://queue:5672 -timeout 5m python main.py
  database:
    image: 'mongo:4.4.0-bionic'
    env_file:
      - environment.env
    expose:
      - '27017'
    volumes:
      - "./mongo-db-vol:/data/db"
  queue:
    image: 'rabbitmq:3.8.6'
    expose:
      - '5672'
