version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - "PORT=5000"
  fetch:
    build: ./fetch
    environment:
      - "SERVER=cnode2.coti.bz"
      - "ROUTE=/transaction/addressTransactions"
      - "ADDRESS=51dbd2feecb8c9e3b5c88129da88156d738d00d57bf4524cc780221c4e414ffc9372b00ad7d75679032d928776b044d40d5febb783d8ac9b241b7c0b1cad77de9b699c23"
      - "DB_USER=root"
      - "DB_PASSWORD=flanks"
    networks:
      - database
  database:
    image: 'mongo'
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=flanks"
    networks:
      - database
    volumes:
      - "./mongo-db-vol:/data/db"

networks:
  database:
