version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - "PORT=5000"
    env_file:
      - environment.env
    networks:
      - default
      - database
    depends_on:
      - database
    command: ./dockerize -wait tcp://database:27017 python main.py
  fetch:
    build: ./fetch
    env_file:
      - environment.env
    networks:
      - database
      - queue
    depends_on:
      - database
      - queue
    command: ./dockerize -wait tcp://database:27017 -wait tcp://queue:5672 sh main.sh
  sheets:
    build: ./sheets
    env_file:
      - environment.env
    networks:
      - database
      - queue
    depends_on:
      - database
      - queue
    command: ./dockerize -wait tcp://database:27017 -wait tcp://queue:5672 python main.py
  database:
    image: 'mongo:4.4.0-bionic'
    env_file:
      - environment.env
    ports: #DEBUG
      - "27017:27017"
    networks:
      - default
      - database
    volumes:
      - "./mongo-db-vol:/data/db"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 10
  queue:
    image: 'rabbitmq:3.8.6'
    ports: #DEBUG
      - "5672:5672"
    networks:
      - default
      - queue
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 30s
      timeout: 10s
      retries: 10
networks:
  database:
  queue:
