version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - "PORT=5000"
    env_file:
      - environment.env
    networks:
      - default
      - database
    depends_on:
      - database
    command: ./dockerize -wait tcp://database:27017 -timeout 5m python main.py
  fetch:
    build: ./fetch
    env_file:
      - environment.env
    networks:
      - database
      - queue
    depends_on:
      - database
      - queue
    command: ./dockerize -wait tcp://database:27017 -wait tcp://queue:5672 -timeout 5m sh main.sh
  sheets:
    build: ./sheets
    env_file:
      - environment.env
    networks:
      - database
      - queue
    depends_on:
      - database
      - queue
    command: ./dockerize -wait tcp://database:27017 -wait tcp://queue:5672 -timeout 5m python main.py
  database:
    image: 'mongo:4.4.0-bionic'
    env_file:
      - environment.env
    ports: #DEBUG
      - "27017:27017"
    networks:
      - default
      - database
    volumes:
      - "./mongo-db-vol:/data/db"
  queue:
    image: 'rabbitmq:3.8.6'
    networks:
      - default
      - queue
networks:
  database:
  queue:
